### ISSUE TITLE
List of terms for broader terms selection autocomplete does not load

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/termit-ui#11] opened 2020-08-14 13:24 UTC
1) new term
2) fill-in details
3) when I want to fill-in broader terms, the list of terms (imported) keeps loading and never finishes:

![image](https://user-images.githubusercontent.com/4235208/90253705-de2db780-de41-11ea-80fb-7184ba35bc49.png)

4) Finish and save without broader terms specified
5) Edit the term again

Now the list loads without problems (in a few seconds):

![image](https://user-images.githubusercontent.com/4235208/90253794-087f7500-de42-11ea-9ba5-5ab91f2185f9.png)

So it seems like a problem with loading the list of terms (imported) when creating a new term. This problem does not appear when an existing term is edited. Is that possible?

I am in this workspace: https://mission-control.netlify.app/workspaces/instance-1926685862

**Comment by ledsoft** [comment] 2020-09-09 15:53
No longer able to reproduce. The referenced workspace does not exist anymore, list of parent terms loads OK when I try it in another workspace. Perhaps it was connected to an issue when terms didn't load at all due to duplicate label in one of the contexts...
Closing, feel free to reopen if the problem occurs again.

**Closed as completed by ledsoft** 2020-09-09 15:53 UTC
Labels: bug
